<script setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import AppButton from '../../../Components/AppButton.vue';
import AttachmentUploader from '../../../Components/AttachmentUploader.vue';
import EmptyState from '../../../Components/EmptyState.vue';
import FormField from '../../../Components/FormField.vue';
import StatusBadge from '../../../Components/StatusBadge.vue';
import AppLayout from '../../../Layouts/AppLayout.vue';

const props = defineProps({ expenses: { type: Array, required: true }, missing_attachments: { type: Array, required: true }, accounts: { type: Array, required: true }, contracts: { type: Array, required: true }, projects: { type: Array, required: true }, idempotencyKey: { type: String, required: true }, cancellationIdempotencyKey: { type: String, required: true }, attachment: { type: Object, required: true } });
const paying = ref(null); const cancelling = ref(null);
const form = useForm({ account_id: '', paid_at: '', payment_mode: 'especes', payment_reference: '', project_id: null, contract_id: null, attachment_ulid: null, is_advance_reimbursement: false, payment_idempotency_key: props.idempotencyKey });
const cancelForm = useForm({ reason: '', payment_idempotency_key: props.cancellationIdempotencyKey });
function localNow() { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
function openPayment(expense) { paying.value = expense; form.reset(); form.paid_at = localNow(); form.payment_idempotency_key = props.idempotencyKey; }
function submit() { form.post(`/finances/paiements-depenses/${paying.value.id}/payer`, { preserveScroll: true, onSuccess: () => { paying.value = null; form.reset(); } }); }
function cancelPayment() { cancelForm.post(`/finances/paiements-depenses/${cancelling.value.id}/annuler`, { preserveScroll: true, onSuccess: () => { cancelling.value = null; cancelForm.reset(); } }); }
</script>

<template>
    <AppLayout title="Paiement des dépenses" active-navigation="finance">
        <div class="grid min-w-0 gap-8">
            <header><h1 class="break-words text-page-title">Paiement des dépenses approuvées</h1><p class="text-ink-secondary">Le paiement reste distinct des deux approbations et appartient uniquement au rôle finance.</p></header>
            <section class="grid gap-3 rounded-xl border border-warning bg-warning-soft p-4"><h2 class="text-section-title">Paiements sans justificatif</h2><p v-if="missing_attachments.length === 0" class="font-semibold">Tous les paiements ont un justificatif.</p><ul v-else class="grid gap-2"><li v-for="expense in missing_attachments" :key="expense.id">Dépense #{{ expense.id }} — {{ expense.requested_amount_label }} — régularisation requise.</li></ul></section>

            <form v-if="paying" class="grid min-w-0 gap-4 rounded-xl border border-primary bg-surface p-4" @submit.prevent="submit"><h2 class="text-section-title">Payer la dépense #{{ paying.id }} — {{ paying.requested_amount_label }}</h2><label class="grid gap-2 font-semibold">Compte débité<select v-model="form.account_id" class="touch-target rounded-lg border border-separator px-3" required><option value="" disabled>Choisir</option><option v-for="account in accounts" :key="account.id" :value="account.id">{{ account.label }}</option></select></label><FormField id="expense-paid-at" v-model="form.paid_at" type="datetime-local" label="Date et heure de paiement" required :error="form.errors.paid_at" /><label class="grid gap-2 font-semibold">Mode<select v-model="form.payment_mode" class="touch-target rounded-lg border border-separator px-3"><option value="especes">Espèces</option><option value="mobile_money">Mobile Money</option><option value="banque">Banque</option><option value="autre">Autre</option></select></label><FormField id="expense-payment-reference" v-model="form.payment_reference" label="Référence facultative" /><label class="grid gap-2 font-semibold">Contrat facultatif<select v-model="form.contract_id" class="touch-target rounded-lg border border-separator px-3"><option :value="null">Aucun</option><option v-for="contract in contracts" :key="contract.id" :value="contract.id">{{ contract.reference }} — {{ contract.title }}</option></select></label><label class="grid gap-2 font-semibold">Projet facultatif<select v-model="form.project_id" class="touch-target rounded-lg border border-separator px-3"><option :value="null">Aucun</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></label><label class="touch-target flex items-center gap-3 rounded-lg border border-separator px-3"><input v-model="form.is_advance_reimbursement" type="checkbox"> Remboursement d’une avance personnelle avec justificatif d’origine</label><AttachmentUploader :attachable-id="attachment.attachable_id" :allowed-types="attachment.allowed_types" :max-size-bytes="attachment.max_size_bytes" @uploaded="form.attachment_ulid = $event.ulid" /><div class="flex flex-wrap gap-2"><AppButton type="submit" variant="principal" :busy="form.processing">Débiter et marquer payée</AppButton><AppButton type="button" variant="secondaire" @click="paying = null">Retour</AppButton></div></form>

            <EmptyState v-if="expenses.length === 0" title="Aucune dépense approuvée à payer." reason="Les dépenses apparaissent après deux approbations distinctes." />
            <ul v-else class="grid min-w-0 gap-4"><li v-for="expense in expenses" :key="expense.id" class="grid min-w-0 gap-3 rounded-xl border border-separator bg-surface p-4"><div class="flex min-w-0 flex-wrap justify-between gap-2"><div><strong>#{{ expense.id }} · {{ expense.reason }}</strong><p>{{ expense.beneficiary }}</p></div><StatusBadge :status="expense.state" /></div><p class="text-xl font-bold">{{ expense.requested_amount_label }}</p><p v-if="expense.account_label">{{ expense.account_label }} · {{ expense.paid_at }}</p><p v-if="expense.contract_reference || expense.project_name">Coût direct : {{ expense.contract_reference || expense.project_name }}</p><div class="flex flex-wrap gap-2"><AppButton v-if="expense.state === 'approuvee'" variant="principal" @click="openPayment(expense)">Payer</AppButton><AppButton v-if="expense.state === 'payee' && !expense.counter_entry_of_id" variant="danger" @click="cancelling = expense">Annuler par contre-écriture</AppButton></div></li></ul>

            <form v-if="cancelling" class="fixed inset-x-3 bottom-3 z-30 grid gap-3 rounded-xl border border-danger bg-surface p-4 shadow-xl sm:left-auto sm:max-w-md" @submit.prevent="cancelPayment"><h2 class="font-bold">Annuler le paiement #{{ cancelling.id }}</h2><label class="grid gap-2 font-semibold">Motif<textarea v-model="cancelForm.reason" class="min-h-24 rounded-lg border border-separator p-3" required minlength="10" /></label><div class="flex flex-wrap gap-2"><AppButton type="submit" variant="danger" :busy="cancelForm.processing">Créer la contre-écriture</AppButton><AppButton type="button" variant="secondaire" @click="cancelling = null">Retour</AppButton></div></form>
        </div>
    </AppLayout>
</template>
