<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import AppButton from '../../../Components/AppButton.vue';
import EmptyState from '../../../Components/EmptyState.vue';
import AppLayout from '../../../Layouts/AppLayout.vue';
const props=defineProps({month:String,monthLabel:String,priorities:Array,canManage:Boolean,emptyMessage:String,priorityOptions:Array});
const form=useForm({month:`${props.month}-01`,title:'',description:'',owner_id:'',indicator:'',target:'',due_date:'',priority:'normale'});
const submit=()=>form.post('/priorites-entreprise',{preserveScroll:true,onSuccess:()=>form.reset('title','description','indicator','target')});
</script>
<template><Head title="Priorités d’entreprise"/><AppLayout title="Priorités d’entreprise"><div class="grid min-w-0 gap-6"><header class="grid min-w-0 gap-2"><h1 class="break-words text-page-title">Priorités d’entreprise — {{ monthLabel }}</h1><p class="text-ink-secondary">Au maximum cinq priorités validées structurent le mois.</p></header><form v-if="canManage" class="grid min-w-0 gap-4 rounded-xl border border-separator bg-surface p-4" @submit.prevent="submit"><h2 class="text-section-title">Créer une priorité</h2><label class="grid gap-1">Titre<input v-model="form.title" required maxlength="160" class="touch-target min-w-0 rounded-lg border border-separator px-3"></label><label class="grid gap-1">Description courte<textarea v-model="form.description" required maxlength="500" class="min-w-0 rounded-lg border border-separator p-3"/></label><div class="grid min-w-0 gap-4 sm:grid-cols-2"><label class="grid gap-1">Responsable (identifiant)<input v-model="form.owner_id" required inputmode="numeric" class="touch-target min-w-0 rounded-lg border border-separator px-3"></label><label class="grid gap-1">Priorité<select v-model="form.priority" class="touch-target min-w-0 rounded-lg border border-separator px-3"><option v-for="option in priorityOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label class="grid gap-1">Indicateur<input v-model="form.indicator" required class="touch-target min-w-0 rounded-lg border border-separator px-3"></label><label class="grid gap-1">Cible<input v-model="form.target" required class="touch-target min-w-0 rounded-lg border border-separator px-3"></label><label class="grid gap-1">Échéance<input v-model="form.due_date" required type="date" class="touch-target min-w-0 rounded-lg border border-separator px-3"></label></div><p v-if="Object.keys(form.errors).length" class="text-danger" role="alert">Corrigez les champs signalés avant de continuer.</p><AppButton type="submit" variant="principal" :busy="form.processing">Créer la priorité</AppButton></form><ul v-if="priorities.length" class="grid min-w-0 gap-3"><li v-for="item in priorities" :key="item.id" class="grid min-w-0 gap-2 rounded-xl border border-separator bg-surface p-4"><div class="flex min-w-0 flex-wrap justify-between gap-2"><h2 class="break-words font-semibold">{{ item.title }}</h2><span class="rounded-full border border-separator px-3 py-1">{{ item.state_label }}</span></div><p class="break-words">{{ item.description }}</p><p class="text-sm text-ink-secondary">{{ item.owner }} · {{ item.priority_label }} · échéance {{ item.due_date }}</p><p><strong>{{ item.indicator }} :</strong> {{ item.target }}</p></li></ul><EmptyState v-else :title="emptyMessage" reason="Les priorités apparaîtront ici dès leur définition." :action-label="canManage?'Créer une priorité':undefined"/></div></AppLayout></template>
