<?php

$roles = ['super_admin', 'direction', 'finance', 'tuteur', 'employe', 'stagiaire'];
$statuses = static function (array $allowedRoles) use ($roles): array {
    $matrix = [];

    foreach ($roles as $role) {
        $matrix[$role] = in_array($role, $allowedRoles, true) ? 204 : 403;
    }

    return $matrix;
};

return [
    'roles' => $roles,
    'prd_source' => [
        'reference' => 'docs/prd.md#43-matrice-daccès',
        'reviewed_on' => '2026-07-20',
        'reviewed_for_milestone' => 'Epic 2',
        'quality_gate_runbook' => 'docs/ops/authorization-quality-gate.md',
    ],
    'access_scopes' => [
        'unauthenticated' => ['status' => 302, 'redirect_route' => 'login'],
        'inactive_account' => ['status' => 302, 'redirect_route' => 'login'],
        'password_change_required' => [
            'status' => 302,
            'redirect_route' => 'password.change.edit',
            'except' => ['password.change.edit', 'password.change.update', 'logout'],
        ],
    ],
    // Routes de socle accessibles à tout compte authentifié actif, sans permission métier.
    'authentication_routes' => [
        'home' => ['method' => 'GET', 'path' => '/'],
        'password.change.edit' => ['method' => 'GET', 'path' => '/mot-de-passe/modifier'],
        'password.change.update' => ['method' => 'PATCH', 'path' => '/mot-de-passe'],
        'logout' => ['method' => 'POST', 'path' => '/deconnexion'],
        'notifications.index' => ['method' => 'GET', 'path' => '/notifications'],
        'notifications.read' => ['method' => 'PATCH', 'path' => '/notifications/{notification}/lue'],
        'notifications.read-all' => ['method' => 'PATCH', 'path' => '/notifications/tout-lu'],
        'expenses.create' => ['method' => 'GET', 'path' => '/depenses/create'],
        'expenses.store' => ['method' => 'POST', 'path' => '/depenses'],
    ],
    'routes' => [
        'daily-reports.today' => ['path' => '/rapports/quotidiens/aujourdhui', 'permission' => 'rapport_quotidien.creer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'daily-reports.index' => ['path' => '/rapports', 'permission' => 'rapport_quotidien.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'blockers.index' => ['path' => '/blocages', 'permission' => 'blocage.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'blockers.store' => ['method' => 'POST', 'path' => '/blocages', 'permission' => 'blocage.creer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'blockers.transition' => ['method' => 'PATCH', 'path' => '/blocages/{blocker}/etat', 'permission' => 'blocage.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'daily-reports.store' => ['method' => 'POST', 'path' => '/rapports/quotidiens', 'permission' => 'rapport_quotidien.creer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'task-requests.store' => ['method' => 'POST', 'path' => '/rapports/{dailyReport}/demandes-tache', 'permission' => 'rapport_quotidien.creer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'task-requests.process' => ['method' => 'PATCH', 'path' => '/demandes-tache/{taskRequest}/traiter', 'permission' => 'tache.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'daily-report-reviews.index' => ['path' => '/rapports/validation', 'permission' => 'rapport_quotidien.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'daily-report-reviews.show' => ['path' => '/rapports/{dailyReport}/validation', 'permission' => 'rapport_quotidien.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'daily-report-reviews.comments.store' => ['method' => 'POST', 'path' => '/rapports/{dailyReport}/commentaires', 'permission' => 'rapport_quotidien.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'daily-report-reviews.validate' => ['method' => 'PATCH', 'path' => '/rapports/{dailyReport}/valider', 'permission' => 'rapport_quotidien.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'daily-report-reviews.return' => ['method' => 'PATCH', 'path' => '/rapports/{dailyReport}/retourner', 'permission' => 'rapport_quotidien.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'weekly-reviews.index' => ['path' => '/revues-hebdomadaires', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'weekly-reviews.show' => ['path' => '/revues-hebdomadaires/{weeklyReview}', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'weekly-reviews.comments.store' => ['method' => 'POST', 'path' => '/revues-hebdomadaires/{weeklyReview}/commentaires', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'weekly-reviews.validate' => ['method' => 'PATCH', 'path' => '/revues-hebdomadaires/{weeklyReview}/valider', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'weekly-reviews.store' => ['method' => 'POST', 'path' => '/revues-hebdomadaires', 'permission' => 'revue_hebdomadaire.gerer', 'statuses' => $statuses(['direction'])],
        'weekly-reviews.objectives.store' => ['method' => 'POST', 'path' => '/revues-hebdomadaires/{weeklyReview}/objectifs', 'permission' => 'revue_hebdomadaire.gerer', 'statuses' => $statuses(['direction'])],
        'weekly-reviews.submit' => ['method' => 'PATCH', 'path' => '/revues-hebdomadaires/{weeklyReview}/soumettre', 'permission' => 'revue_hebdomadaire.gerer', 'statuses' => $statuses(['direction'])],
        'improvement-plans.index' => ['path' => '/plans-accompagnement', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'improvement-plans.show' => ['path' => '/plans-accompagnement/{improvementPlan}', 'permission' => 'revue_hebdomadaire.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'improvement-plans.store' => ['method' => 'POST', 'path' => '/revues-hebdomadaires/{weeklyReview}/plans-accompagnement', 'permission' => 'revue_hebdomadaire.gerer', 'statuses' => $statuses(['direction'])],
        'improvement-plans.close' => ['method' => 'PATCH', 'path' => '/plans-accompagnement/{improvementPlan}/terminer', 'permission' => 'revue_hebdomadaire.gerer', 'statuses' => $statuses(['direction'])],
        'internship-intakes.index' => ['path' => '/stages/fiches-entree', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'internship-intakes.show' => ['path' => '/stages/fiches-entree/{internshipIntakeForm}', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'internship-intakes.store' => ['method' => 'POST', 'path' => '/stages/fiches-entree', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internship-intakes.submit' => ['method' => 'PATCH', 'path' => '/stages/fiches-entree/{internshipIntakeForm}/soumettre', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internship-intakes.decide' => ['method' => 'PATCH', 'path' => '/stages/fiches-entree/{internshipIntakeForm}/decision', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'interns.activate' => ['method' => 'POST', 'path' => '/stages/stagiaires/{user}/activer', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'tutors.capacity' => ['path' => '/tuteurs/charge', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internships.index' => ['path' => '/stages', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'support-slots.index' => ['path' => '/creneaux-suivi', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'support-slots.store' => ['method' => 'POST', 'path' => '/creneaux-suivi', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'internships.show' => ['path' => '/stages/{internship}', 'permission' => 'stagiaire.consulter', 'statuses' => $statuses(['direction', 'tuteur', 'stagiaire'])],
        'internships.plan.save' => ['method' => 'PUT', 'path' => '/stages/{internship}/plan', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internships.evaluations.store' => ['method' => 'POST', 'path' => '/stages/{internship}/evaluations', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internships.evaluations.validate' => ['method' => 'PATCH', 'path' => '/stages/{internship}/evaluations/{evaluation}/valider', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'internships.exit' => ['method' => 'PATCH', 'path' => '/stages/{internship}/sortie', 'permission' => 'stagiaire.gerer', 'statuses' => $statuses(['direction', 'tuteur'])],
        'company-priorities.index' => ['path' => '/priorites-entreprise', 'permission' => 'objectif_entreprise.consulter', 'statuses' => $statuses(['super_admin', 'direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'company-priorities.store' => ['method' => 'POST', 'path' => '/priorites-entreprise', 'permission' => 'objectif_entreprise.gerer', 'statuses' => $statuses(['direction'])],
        'company-priorities.update' => ['method' => 'PATCH', 'path' => '/priorites-entreprise/{companyPriority}', 'permission' => 'objectif_entreprise.gerer', 'statuses' => $statuses(['direction'])],
        'company-priorities.cancel' => ['method' => 'PATCH', 'path' => '/priorites-entreprise/{companyPriority}/annuler', 'permission' => 'objectif_entreprise.gerer', 'statuses' => $statuses(['direction'])],
        'objectives.index' => ['path' => '/objectifs', 'permission' => 'objectif_individuel.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.calendar' => ['path' => '/objectifs/calendrier', 'permission' => 'objectif_individuel.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.summary' => ['path' => '/objectifs/synthese', 'permission' => 'objectif_individuel.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.show' => ['path' => '/objectifs/{objective}', 'permission' => 'objectif_individuel.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.store' => ['method' => 'POST', 'path' => '/objectifs', 'permission' => 'objectif_individuel.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.update' => ['method' => 'PATCH', 'path' => '/objectifs/{objective}', 'permission' => 'objectif_individuel.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.validate' => ['method' => 'PATCH', 'path' => '/objectifs/{objective}/valider', 'permission' => 'objectif.valider', 'statuses' => $statuses(['direction', 'tuteur'])],
        'objectives.transition' => ['method' => 'PATCH', 'path' => '/objectifs/{objective}/etat', 'permission' => 'objectif_individuel.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.copy' => ['method' => 'POST', 'path' => '/objectifs/{objective}/copier', 'permission' => 'objectif_individuel.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'objectives.comments.store' => ['method' => 'POST', 'path' => '/objectifs/{objective}/commentaires', 'permission' => 'objectif_individuel.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.index' => ['path' => '/projets', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.store' => ['method' => 'POST', 'path' => '/projets', 'permission' => 'projet.gerer', 'statuses' => $statuses(['direction'])],
        'projects.show' => ['path' => '/projets/{project}', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.budget' => ['path' => '/projets/{project}/budget', 'permission' => 'projet.budget.consulter', 'statuses' => $statuses(['direction', 'finance'])],
        'projects.transition' => ['method' => 'PATCH', 'path' => '/projets/{project}/etat', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.members.update' => ['method' => 'PATCH', 'path' => '/projets/{project}/membres', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.comments.store' => ['method' => 'POST', 'path' => '/projets/{project}/commentaires', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.links.store' => ['method' => 'POST', 'path' => '/projets/{project}/liens', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'projects.attachments.store' => ['method' => 'POST', 'path' => '/projets/{project}/pieces-jointes', 'permission' => 'projet.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.index' => ['path' => '/taches', 'permission' => 'tache.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.today' => ['path' => '/taches/aujourdhui', 'permission' => 'tache.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.show' => ['path' => '/taches/{task}', 'permission' => 'tache.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.store' => ['method' => 'POST', 'path' => '/taches', 'permission' => 'tache.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.comments.store' => ['method' => 'POST', 'path' => '/taches/{task}/commentaires', 'permission' => 'tache.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.links.store' => ['method' => 'POST', 'path' => '/taches/{task}/liens', 'permission' => 'tache.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'tasks.attachments.store' => ['method' => 'POST', 'path' => '/taches/{task}/pieces-jointes', 'permission' => 'tache.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'deliverables.index' => ['path' => '/livrables', 'permission' => 'livrable.consulter', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'deliverables.store' => ['method' => 'POST', 'path' => '/livrables', 'permission' => 'livrable.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'deliverables.transition' => ['method' => 'PATCH', 'path' => '/livrables/{deliverable}/etat', 'permission' => 'livrable.gerer', 'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire'])],
        'absences.index' => [
            'path' => '/absences',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'absences.show' => [
            'path' => '/absences/{absence}',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'absences.store' => [
            'method' => 'POST',
            'path' => '/absences',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'absences.approve' => [
            'method' => 'PATCH',
            'path' => '/absences/{absence}/approuver',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'absences.refuse' => [
            'method' => 'PATCH',
            'path' => '/absences/{absence}/refuser',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'absences.cancel' => [
            'method' => 'PATCH',
            'path' => '/absences/{absence}/annuler',
            'permission' => 'absence.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'calendar.index' => [
            'path' => '/calendrier',
            'permission' => 'calendrier.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'holidays.store' => [
            'method' => 'POST',
            'path' => '/calendrier/jours-feries',
            'permission' => 'calendrier.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'holidays.update' => [
            'method' => 'PATCH',
            'path' => '/calendrier/jours-feries/{holiday}',
            'permission' => 'calendrier.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'holidays.deactivate' => [
            'method' => 'PATCH',
            'path' => '/calendrier/jours-feries/{holiday}/desactiver',
            'permission' => 'calendrier.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'holidays.reactivate' => [
            'method' => 'PATCH',
            'path' => '/calendrier/jours-feries/{holiday}/reactiver',
            'permission' => 'calendrier.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'internal-documents.index' => [
            'path' => '/documents-internes',
            'permission' => 'document_interne.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'internal-documents.show' => [
            'path' => '/documents-internes/{internalDocument}',
            'permission' => 'document_interne.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'internal-documents.store' => [
            'method' => 'POST',
            'path' => '/documents-internes',
            'permission' => 'document_interne.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'internal-documents.versions.store' => [
            'method' => 'POST',
            'path' => '/documents-internes/{internalDocument}/versions',
            'permission' => 'document_interne.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'internal-documents.acknowledge' => [
            'method' => 'POST',
            'path' => '/documents-internes/{internalDocument}/accepter',
            'permission' => 'document_interne.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'internal-documents.acknowledgements' => [
            'path' => '/documents-internes/{internalDocument}/acceptations',
            'permission' => 'document_interne.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'people.show' => [
            'path' => '/personnes/{person}',
            'permission' => 'fiche.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'people.history' => [
            'path' => '/personnes/{person}/historique',
            'permission' => 'fiche.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'people.update' => [
            'method' => 'PATCH',
            'path' => '/personnes/{person}',
            'permission' => 'fiche.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'people.documents.index' => [
            'path' => '/personnes/{person}/documents',
            'permission' => 'fiche.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'people.documents.store' => [
            'method' => 'POST',
            'path' => '/personnes/{person}/documents',
            'permission' => 'fiche.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'people.documents.show' => [
            'path' => '/personnes/{person}/documents/{document}',
            'permission' => 'fiche.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'people.documents.archive' => [
            'method' => 'PATCH',
            'path' => '/personnes/{person}/documents/{document}/archiver',
            'permission' => 'fiche.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'attachments.store' => [
            'method' => 'POST',
            'path' => '/internal/v1/attachments',
            'permission' => 'piece_jointe.creer',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'attachments.show' => [
            'path' => '/pieces-jointes/{attachment}',
            'permission' => 'piece_jointe.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'settings.index' => [
            'path' => '/parametres',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'settings.update' => [
            'method' => 'PATCH',
            'path' => '/parametres',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'settings.preview' => [
            'method' => 'POST',
            'path' => '/parametres/apercu',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'expense-categories.index' => [
            'path' => '/categories-depense',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'expense-categories.store' => [
            'method' => 'POST',
            'path' => '/categories-depense',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'expense-categories.update' => [
            'method' => 'PATCH',
            'path' => '/categories-depense/{expenseCategory}',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'expense-categories.deactivate' => [
            'method' => 'PATCH',
            'path' => '/categories-depense/{expenseCategory}/desactiver',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'expense-categories.reactivate' => [
            'method' => 'PATCH',
            'path' => '/categories-depense/{expenseCategory}/reactiver',
            'permission' => 'parametre.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'organisation.index' => [
            'path' => '/organisation',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.company.update' => [
            'method' => 'PATCH',
            'path' => '/organisation/entreprise',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.departments.store' => [
            'method' => 'POST',
            'path' => '/organisation/services',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.departments.update' => [
            'method' => 'PATCH',
            'path' => '/organisation/services/{department}',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.departments.deactivate' => [
            'method' => 'PATCH',
            'path' => '/organisation/services/{department}/desactiver',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.departments.reactivate' => [
            'method' => 'PATCH',
            'path' => '/organisation/services/{department}/reactiver',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.functions.store' => [
            'method' => 'POST',
            'path' => '/organisation/fonctions',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.functions.update' => [
            'method' => 'PATCH',
            'path' => '/organisation/fonctions/{jobFunction}',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.functions.deactivate' => [
            'method' => 'PATCH',
            'path' => '/organisation/fonctions/{jobFunction}/desactiver',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'organisation.functions.reactivate' => [
            'method' => 'PATCH',
            'path' => '/organisation/fonctions/{jobFunction}/reactiver',
            'permission' => 'organisation.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'accounts.index' => [
            'path' => '/comptes',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'accounts.store' => [
            'method' => 'POST',
            'path' => '/comptes',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'accounts.roles.sync' => [
            'method' => 'PATCH',
            'path' => '/comptes/{user}/roles',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'accounts.archive' => [
            'method' => 'PATCH',
            'path' => '/comptes/{user}/archiver',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'accounts.password-reinitialization.initiate' => [
            'method' => 'POST',
            'path' => '/comptes/{user}/reinitialisation/initier',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'accounts.password-reinitialization.confirm' => [
            'method' => 'POST',
            'path' => '/comptes/{user}/reinitialisation/confirmer',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
        ],
        'login-attempts.index' => [
            'path' => '/connexions',
            'permission' => 'connexion.consulter',
            'statuses' => $statuses(['direction']),
        ],
        'audit.index' => [
            'path' => '/journal-audit',
            'permission' => 'audit.consulter',
            'statuses' => $statuses(['direction']),
        ],
        'audit.export' => [
            'path' => '/journal-audit/export',
            'permission' => 'audit.consulter',
            'statuses' => $statuses(['direction']),
        ],
        'financial-accounts.index' => [
            'path' => '/finances/comptes',
            'permission' => 'compte_financier.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'financial-accounts.store' => [
            'method' => 'POST',
            'path' => '/finances/comptes',
            'permission' => 'compte_financier.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'financial-accounts.deactivate' => [
            'method' => 'PATCH',
            'path' => '/finances/comptes/{account}/desactiver',
            'permission' => 'compte_financier.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'fixed-charges.index' => [
            'path' => '/finances/charges-fixes',
            'permission' => 'charge_fixe.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'fixed-charges.preview' => [
            'method' => 'POST',
            'path' => '/finances/charges-fixes/apercu',
            'permission' => 'charge_fixe.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'fixed-charges.store' => [
            'method' => 'POST',
            'path' => '/finances/charges-fixes',
            'permission' => 'charge_fixe.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'fixed-charges.update' => [
            'method' => 'PATCH',
            'path' => '/finances/charges-fixes/{fixedCharge}',
            'permission' => 'charge_fixe.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'clients.index' => [
            'path' => '/finances/clients',
            'permission' => 'client.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'clients.store' => [
            'method' => 'POST',
            'path' => '/finances/clients',
            'permission' => 'client.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'clients.update' => [
            'method' => 'PATCH',
            'path' => '/finances/clients/{client}',
            'permission' => 'client.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'contracts.index' => [
            'path' => '/finances/contrats',
            'permission' => 'client.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'contracts.store' => [
            'method' => 'POST',
            'path' => '/finances/contrats',
            'permission' => 'client.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'contracts.update' => [
            'method' => 'PATCH',
            'path' => '/finances/contrats/{contract}',
            'permission' => 'client.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'contracts.close' => [
            'method' => 'POST',
            'path' => '/finances/contrats/{contract}/cloturer',
            'permission' => 'client.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'monthly-budgets.index' => [
            'path' => '/finances/budgets-mensuels',
            'permission' => 'budget_financier.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'monthly-budgets.store' => [
            'method' => 'POST',
            'path' => '/finances/budgets-mensuels',
            'permission' => 'budget_financier.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'invoices.index' => [
            'path' => '/finances/factures',
            'permission' => 'facture.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'invoices.store' => [
            'method' => 'POST',
            'path' => '/finances/factures',
            'permission' => 'facture.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'invoices.cancel' => [
            'method' => 'PATCH',
            'path' => '/finances/factures/{invoice}/annuler',
            'permission' => 'facture.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'payments.index' => [
            'path' => '/finances/encaissements',
            'permission' => 'encaissement.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'payments.store' => [
            'method' => 'POST',
            'path' => '/finances/encaissements',
            'permission' => 'encaissement.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'payments.correct' => [
            'method' => 'POST',
            'path' => '/finances/encaissements/{payment}/corriger',
            'permission' => 'encaissement.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'payments.cancel' => [
            'method' => 'POST',
            'path' => '/finances/encaissements/{payment}/annuler',
            'permission' => 'encaissement.gerer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'expense-payments.index' => [
            'path' => '/finances/paiements-depenses',
            'permission' => 'depense.payer',
            'statuses' => $statuses(['finance']),
        ],
        'expense-payments.pay' => [
            'method' => 'POST',
            'path' => '/finances/paiements-depenses/{expense}/payer',
            'permission' => 'depense.payer',
            'statuses' => $statuses(['finance']),
        ],
        'expense-payments.cancel' => [
            'method' => 'POST',
            'path' => '/finances/paiements-depenses/{expense}/annuler',
            'permission' => 'depense.payer',
            'statuses' => $statuses(['finance']),
        ],
        'shares.index' => [
            'path' => '/finances/parts',
            'permission' => 'part.consulter',
            'statuses' => $statuses(['direction', 'finance', 'employe']),
        ],
        'shares.show' => [
            'path' => '/finances/parts/{shareEntitlement}',
            'permission' => 'part.consulter',
            'statuses' => $statuses(['direction', 'finance', 'employe']),
        ],
        'shares.request-payment' => [
            'method' => 'POST',
            'path' => '/finances/parts/{shareEntitlement}/demander-versement',
            'permission' => 'part.consulter',
            'statuses' => $statuses(['direction', 'finance', 'employe']),
        ],
        // Registre des parts de contribution : la direction, et elle seule. Ni finance ni
        // super_admin n'y accèdent — ce registre décrit la propriété de l'entreprise.
        'contribution-shares.index' => [
            'path' => '/finances/parts-de-contribution',
            'permission' => 'part_contribution.consulter',
            'statuses' => $statuses(['direction']),
        ],
        'capital-contributions.store' => [
            'method' => 'POST',
            'path' => '/finances/parts-de-contribution/apports',
            'permission' => 'part_contribution.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'capital-contributions.approve' => [
            'method' => 'PATCH',
            'path' => '/finances/parts-de-contribution/apports/{capitalContribution}/approuver',
            'permission' => 'part_contribution.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'capital-contributions.refuse' => [
            'method' => 'PATCH',
            'path' => '/finances/parts-de-contribution/apports/{capitalContribution}/refuser',
            'permission' => 'part_contribution.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'reserve.index' => [
            'path' => '/finances/reserve',
            'permission' => 'reserve.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'reserve.usages.store' => [
            'method' => 'POST',
            'path' => '/finances/reserve/utilisations',
            'permission' => 'reserve.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'reserve.usages.approve' => [
            'method' => 'PATCH',
            'path' => '/finances/reserve/mouvements/{reserveMovement}/approuver',
            'permission' => 'reserve.gerer',
            'statuses' => $statuses(['direction']),
        ],
        'reconciliations.index' => [
            'path' => '/finances/rapprochements',
            'permission' => 'rapprochement.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'reconciliations.store' => [
            'method' => 'POST',
            'path' => '/finances/rapprochements',
            'permission' => 'rapprochement.preparer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'reconciliations.validate' => [
            'method' => 'PATCH',
            'path' => '/finances/rapprochements/{reconciliation}/valider',
            'permission' => 'rapprochement.controler',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'reconciliations.correct' => [
            'method' => 'POST',
            'path' => '/finances/rapprochements/{reconciliation}/corriger',
            'permission' => 'rapprochement.preparer',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'financial-reports.index' => [
            'path' => '/finances/rapports-mensuels',
            'permission' => 'rapport_financier.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'financial-reports.store' => [
            'method' => 'POST',
            'path' => '/finances/rapports-mensuels',
            'permission' => 'rapport_financier.preparer',
            'statuses' => $statuses(['finance']),
        ],
        'financial-reports.control' => [
            'method' => 'PATCH',
            'path' => '/finances/rapports-mensuels/{monthlyReport}/controler',
            'permission' => 'rapport_financier.controler',
            'statuses' => $statuses(['finance']),
        ],
        'financial-reports.validate' => [
            'method' => 'PATCH',
            'path' => '/finances/rapports-mensuels/{monthlyReport}/valider',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],
        'financial-reports.reopen' => [
            'method' => 'PATCH',
            'path' => '/finances/rapports-mensuels/{monthlyReport}/reouvrir',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],
        'expenses.index' => [
            'path' => '/depenses',
            'permission' => 'depense.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'expenses.show' => [
            'path' => '/depenses/{expense}',
            'permission' => 'depense.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'expenses.update' => [
            'method' => 'PATCH',
            'path' => '/depenses/{expense}',
            'permission' => 'depense.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'expenses.cancel' => [
            'method' => 'PATCH',
            'path' => '/depenses/{expense}/annuler',
            'permission' => 'depense.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'expenses.approvals.index' => [
            'path' => '/depenses/approbations',
            'permission' => 'depense.approuver',
            'statuses' => $statuses(['direction']),
        ],
        'expenses.approvals.show' => [
            'path' => '/depenses/{expense}/decision',
            'permission' => 'depense.approuver',
            'statuses' => $statuses(['direction']),
        ],
        'expenses.approvals.attachment' => [
            'path' => '/depenses/{expense}/decision/justificatif',
            'permission' => 'depense.approuver',
            'statuses' => $statuses(['direction']),
        ],
        'expenses.approve' => [
            'method' => 'PATCH',
            'path' => '/depenses/{expense}/approuver',
            'permission' => 'depense.approuver',
            'statuses' => $statuses(['direction']),
        ],
        'expenses.refuse' => [
            'method' => 'PATCH',
            'path' => '/depenses/{expense}/refuser',
            'permission' => 'depense.approuver',
            'statuses' => $statuses(['direction']),
        ],

        // Story 9.1 — alertes, plans correctifs et tableaux de bord consolidés.
        // Le tableau de bord financier est réservé à `finance` et `direction` (AC 22) ; le
        // tableau de bord direction remplace la fixture `testing.authorization.dashboard-global.view`.
        'dashboard.finance' => [
            'path' => '/finances/tableau-de-bord',
            'permission' => 'tableau_bord_financier.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'dashboard.direction' => [
            'path' => '/tableau-de-bord/direction',
            'permission' => 'tableau_bord_global.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur']),
        ],
        'correction-plans.index' => [
            'path' => '/finances/plans-correctifs',
            'permission' => 'rapport_financier.consulter',
            'statuses' => $statuses(['direction', 'finance']),
        ],
        'correction-plans.create' => [
            'path' => '/finances/plans-correctifs/nouveau',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],
        'correction-plans.store' => [
            'method' => 'POST',
            'path' => '/finances/plans-correctifs',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],
        'correction-plans.validate' => [
            'method' => 'PATCH',
            'path' => '/finances/plans-correctifs/{correctionPlan}/valider',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],
        'correction-plans.revise' => [
            'method' => 'POST',
            'path' => '/finances/plans-correctifs/{correctionPlan}/reviser',
            'permission' => 'rapport_financier.valider',
            'statuses' => $statuses(['direction']),
        ],

        // Story 10.1 — recherche, listes filtrables et exports CSV.
        // `search.index` remplace la fixture `testing.authorization.search`.
        'search.index' => [
            'path' => '/recherche',
            'permission' => 'recherche.utiliser',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        // Une seule route sert les quatre listes. La permission effective est celle de la liste
        // demandée, appliquée par `ListingRequest` ; la matrice déclare ici la plus large,
        // `depense.consulter`, que tous les rôles métier détiennent. Le cloisonnement liste par
        // liste est prouvé séparément par `ListingAndExportHttpTest`.
        'listing.index' => [
            'path' => '/listes/{liste}',
            'permission' => 'depense.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'exports.create' => [
            'path' => '/listes/{liste}/export',
            'permission' => 'export.creer',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
        ],
        'saved-filters.store' => [
            'method' => 'POST',
            'path' => '/filtres-enregistres',
            'permission' => 'tableau_bord_global.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur']),
        ],
        'saved-filters.deactivate' => [
            'method' => 'PATCH',
            'path' => '/filtres-enregistres/{savedFilter}/retirer',
            'permission' => 'tableau_bord_global.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur']),
        ],
    ],
    // Contrats provisoires : chaque fixture disparaît dès que sa route réelle de remplacement existe.
    'fixtures' => [
        'testing.authorization.dashboard.view' => [
            'path' => '/__test/authorization/dashboard',
            'permission' => 'tableau_bord.consulter',
            'statuses' => $statuses(['direction', 'finance', 'tuteur', 'employe', 'stagiaire']),
            'replacement' => ['route' => 'dashboard.index', 'story' => '5.8'],
        ],
        'testing.authorization.account.manage' => [
            'path' => '/__test/authorization/accounts',
            'permission' => 'compte.gerer|compte.technique.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
            'replacement' => ['route' => 'authorization.accounts.index', 'story' => '10.4'],
        ],
        'testing.authorization.role.manage' => [
            'path' => '/__test/authorization/roles',
            'permission' => 'role.gerer',
            'statuses' => $statuses(['super_admin', 'direction']),
            'replacement' => ['route' => 'authorization.roles.index', 'story' => '10.4'],
        ],
        'testing.authorization.intern.view' => [
            'path' => '/__test/authorization/interns',
            'permission' => 'stagiaire.consulter',
            'statuses' => $statuses(['direction', 'tuteur', 'stagiaire']),
            'replacement' => ['route' => 'interns.index', 'story' => '7.3'],
        ],
        'testing.authorization.finance-entry.view' => [
            'path' => '/__test/authorization/finance-entries',
            'permission' => 'finance.ecriture.consulter',
            'statuses' => $statuses(['direction', 'finance', 'employe', 'stagiaire']),
            'replacement' => ['route' => 'finance.entries.index', 'story' => '8.1'],
        ],
    ],
];
