<?php

$roles = [
    'super_admin' => [
        'compte.technique.gerer',
        'role.gerer',
        'parametre.gerer',
        'journal_technique.consulter',
        'objectif_entreprise.consulter',
    ],
    'direction' => [
        'piece_jointe.consulter',
        'piece_jointe.creer',
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'tableau_bord_financier.consulter',
        'compte.consulter',
        'compte.gerer',
        'fiche.consulter',
        'fiche.gerer',
        'role.gerer',
        'parametre.gerer',
        'calendrier.gerer',
        'objectif_entreprise.consulter',
        'objectif_entreprise.gerer',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'organisation.gerer',
        'objectif.valider',
        'projet.consulter',
        'projet.gerer',
        'projet.budget.consulter',
        'tache.consulter',
        'tache.gerer',
        'livrable.consulter',
        'livrable.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.gerer',
        'rapport_quotidien.creer',
        'rapport_quotidien.valider',
        'revue_hebdomadaire.consulter',
        'revue_hebdomadaire.gerer',
        'blocage.consulter',
        'blocage.creer',
        'blocage.gerer',
        'stagiaire.consulter',
        'stagiaire.gerer',
        'absence.consulter',
        'absence.gerer',
        'document_interne.consulter',
        'document_interne.gerer',
        'depense.consulter',
        'depense.approuver',
        'finance.ecriture.consulter',
        'finance.ecriture.creer',
        'compte_financier.consulter',
        'compte_financier.gerer',
        'charge_fixe.consulter',
        'charge_fixe.gerer',
        'client.consulter',
        'client.gerer',
        'facture.consulter',
        'facture.gerer',
        'encaissement.consulter',
        'encaissement.gerer',
        'connexion.consulter',
        'part.consulter',
        'part.gerer',
        'budget_financier.consulter',
        'budget_financier.gerer',
        'rapprochement.consulter',
        'rapprochement.preparer',
        'rapprochement.controler',
        'reserve.consulter',
        'reserve.gerer',
        'rapport_financier.consulter',
        'rapport_financier.valider',
        'audit.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
    'finance' => [
        'piece_jointe.consulter',
        'piece_jointe.creer',
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'tableau_bord_financier.consulter',
        'fiche.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'projet.consulter',
        'projet.budget.consulter',
        'tache.consulter',
        'tache.gerer',
        'livrable.consulter',
        'livrable.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.creer',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'blocage.creer',
        'blocage.gerer',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.preparer',
        'depense.payer',
        'finance.ecriture.consulter',
        'finance.ecriture.creer',
        'compte_financier.consulter',
        'compte_financier.gerer',
        'charge_fixe.consulter',
        'charge_fixe.gerer',
        'client.consulter',
        'client.gerer',
        'facture.consulter',
        'facture.gerer',
        'encaissement.consulter',
        'encaissement.gerer',
        'part.consulter',
        'part.gerer',
        'budget_financier.consulter',
        'budget_financier.gerer',
        'rapprochement.consulter',
        'rapprochement.preparer',
        'rapprochement.controler',
        'reserve.consulter',
        'reserve.preparer',
        'rapport_financier.consulter',
        'rapport_financier.preparer',
        'rapport_financier.controler',
        'recherche.utiliser',
        'export.creer',
    ],
    'tuteur' => [
        'piece_jointe.consulter',
        'piece_jointe.creer',
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'fiche.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'objectif.valider',
        'projet.consulter',
        'tache.consulter',
        'tache.gerer',
        'livrable.consulter',
        'livrable.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.creer',
        'rapport_quotidien.valider',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'blocage.creer',
        'blocage.gerer',
        'stagiaire.consulter',
        'stagiaire.gerer',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'recherche.utiliser',
        'export.creer',
    ],
    'employe' => [
        'piece_jointe.consulter',
        'piece_jointe.creer',
        'tableau_bord.consulter',
        'fiche.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'projet.consulter',
        'tache.consulter',
        'tache.gerer',
        'livrable.consulter',
        'livrable.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.creer',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'blocage.creer',
        'blocage.gerer',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'finance.ecriture.consulter',
        'part.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
    'stagiaire' => [
        'piece_jointe.consulter',
        'piece_jointe.creer',
        'tableau_bord.consulter',
        'fiche.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'projet.consulter',
        'tache.consulter',
        'tache.gerer',
        'livrable.consulter',
        'livrable.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.creer',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'blocage.creer',
        'blocage.gerer',
        'stagiaire.consulter',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'finance.ecriture.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
];

// Union des permissions de tous les rôles, dédupliquée. La boucle remplace un
// `array_merge(...array_values($roles))` : au-delà d'une certaine taille, l'analyse statique perd
// la forme de liste des tableaux littéraux et refuse l'appel variadique.
$permissions = [];

foreach ($roles as $rolePermissions) {
    foreach ($rolePermissions as $permission) {
        $permissions[$permission] = true;
    }
}

$permissions = array_keys($permissions);
sort($permissions);

return [
    'guard' => 'web',
    'roles' => $roles,
    'permissions' => $permissions,
];
