<?php

$roles = [
    'super_admin' => [
        'compte.technique.gerer',
        'role.gerer',
        'parametre.gerer',
        'journal_technique.consulter',
    ],
    'direction' => [
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'compte.consulter',
        'compte.gerer',
        'role.gerer',
        'parametre.gerer',
        'objectif_entreprise.consulter',
        'objectif_entreprise.gerer',
        'objectif_individuel.consulter',
        'objectif_individuel.gerer',
        'objectif.valider',
        'projet.consulter',
        'projet.gerer',
        'rapport_quotidien.consulter',
        'rapport_quotidien.gerer',
        'revue_hebdomadaire.consulter',
        'revue_hebdomadaire.gerer',
        'blocage.consulter',
        'blocage.gerer',
        'stagiaire.consulter',
        'stagiaire.gerer',
        'absence.consulter',
        'absence.gerer',
        'document_interne.consulter',
        'document_interne.gerer',
        'depense.consulter',
        'depense.approuver',
        'finance.ecriture.consulter',
        'finance.ecriture.creer',
        'client.consulter',
        'client.gerer',
        'part.consulter',
        'part.gerer',
        'reserve.consulter',
        'reserve.gerer',
        'rapport_financier.consulter',
        'rapport_financier.valider',
        'audit.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
    'finance' => [
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'projet.consulter',
        'rapport_quotidien.consulter',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.preparer',
        'depense.payer',
        'finance.ecriture.consulter',
        'finance.ecriture.creer',
        'client.consulter',
        'client.gerer',
        'part.consulter',
        'part.gerer',
        'reserve.consulter',
        'reserve.preparer',
        'rapport_financier.consulter',
        'rapport_financier.preparer',
        'rapport_financier.controler',
        'recherche.utiliser',
        'export.creer',
    ],
    'tuteur' => [
        'tableau_bord.consulter',
        'tableau_bord_global.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'projet.consulter',
        'rapport_quotidien.consulter',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'stagiaire.consulter',
        'stagiaire.gerer',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'recherche.utiliser',
        'export.creer',
    ],
    'employe' => [
        'tableau_bord.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'projet.consulter',
        'rapport_quotidien.consulter',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'finance.ecriture.consulter',
        'part.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
    'stagiaire' => [
        'tableau_bord.consulter',
        'objectif_entreprise.consulter',
        'objectif_individuel.consulter',
        'projet.consulter',
        'rapport_quotidien.consulter',
        'revue_hebdomadaire.consulter',
        'blocage.consulter',
        'stagiaire.consulter',
        'absence.consulter',
        'document_interne.consulter',
        'depense.consulter',
        'depense.creer',
        'finance.ecriture.consulter',
        'recherche.utiliser',
        'export.creer',
    ],
];

$permissions = array_values(array_unique(array_merge(...array_values($roles))));
sort($permissions);

return [
    'guard' => 'web',
    'roles' => $roles,
    'permissions' => $permissions,
];
